name: infinotate
description: An infinite canvas drawing app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.7.0

dependencies:
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  epub_view: ^3.2.0
  flutter_epub_viewer: ^1.2.1
  # vocsy_epub_viewer: ^3.0.0  # Removed
  # file_picker: ^6.2.1  # Temporarily commented out

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add assets
  assets:
    - assets/
    - assets/books/